openapi: "3.0.0"

info:
  title: Stress-ng REST API
  version: "1.0"
servers:
  - url: http://localhost:8080/v1.0

paths:
  /health/liveness:
    get:
      summary: Liveness probe handle
      operationId: api.liveness
      responses:
        200:
          description: Successful liveness
          content:
            text/plain:
              schema:
                type: string
                example: "iamok"
  /health/readiness:
    get:
      summary: Readiness probe handle
      operationId: api.readiness
      responses:
        200:
          description: Successful readiness probe
          content:
            text/plain:
              schema:
                type: string
                example: "ready"
        503:
          description: Failed readiness probe
          content:
            text/plain:
              schema:
                type: string
                example: "retcode: X\n{stress-ng error}"
  /runjob:
    post:
      summary: Send stress-ng jobfile to run it
      operationId: api.runjob
      requestBody:
        description: Stress-ng jobfile in plain text. [More examples](https://github.com/ColinIanKing/stress-ng/tree/master/example-jobs).
        content:
          text/plain:
            schema:
              x-body-name: jobfile # TODO move under 'requestBody' after next connexion update
              type: string
              example: |
                  vm 1
                  timeout 1s

      responses:
        200:
          description: Successful run
          content:
            application/json:
              schema:
                type: string
                example:
                  info: stress-ng result
                  retcode: 0
        503:
          description: Unsuccessful run
          content:
            application/json:
              schema:
                type: string
                example:
                  info: some error
                  retcode: "!=0"
