apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stress-api.fullname" . }}
  labels:
    {{- include "stress-api.labels" . | nindent 4 }}
type: Opaque
data:
  key: "{{ .Values.apiSecret | b64enc }}"
