name: Build, test, push

# TODO create dedicated housekeeping workflow
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Leave it here for debug
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=schedule
          flavor: |
            latest=${{ github.ref_name == 'master' }}
            prefix=
            suffix=

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run stress-api container
        run: docker run -d -p 80:80 --name sng ${{ fromJSON(steps.meta.outputs.json).tags[0] }}

      - name: Test readiness
        run: |
          sleep 3 && \
          curl -X 'GET' 'http://localhost:80/v1.0/health/readiness' \
          -H 'Accept: text/plain' \
          -H 'Content-Type: text/plain'

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
